<main role="main">
    <div class="jumbotron contato">
        <div class="container">
            <h2 class="display-4 text-center" style="margin-bottom: 50px;">Faça seu orçamento</h2>                
            <form method="POST" id="form-contato" name="form-contato" action="clarim/salvarContato" >
                <div class="form-row">
                    <div class="form-group col-md-6 form-nome">
                        <label>Nome</label>
                        <input type="text" name="nome" class="form-control" placeholder="Nome" value="" required>
                    </div>
                    <div class="form-group col-md-6 form-email">
                        <label>E-mail</label>
                        <input type="email" name="email" class="form-control" placeholder="Seu melhor e-mail" value="" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 form-assunto">
                        <label>Assunto</label>
                        <input type="text" name="assunto" class="form-control" placeholder="Assunto da mensagem" value="" required>
                    </div>
                    <div class="form-group col-md-6 form-telefone">
                        <label>Telefone</label>
                        <input type="text" name="telefone" class="form-control" placeholder="Telefone para contato" value="" required>
                    </div>
                </div>
                <div class="form-group mensagem">
                    <label>Mensagem</label>
                    <textarea name="mensagem" class="form-control" rows="5"></textarea>
                    <small> * minimo 10 caracteres</small>
                </div>
                <input type="submit" name="SendCadCont" class="btn btn-primary" value="Enviar">
                <?php
                    if($this->view->erroCadastro){ 
                        ?>
                        <small class="form-text text-danger">*Erro ao tentar registrar a mensagem, 
                            verifique se os campos foram preenchidos corretamente</small>
                        <?php
                    }
                ?>
            </form>

        </div>
    </div>
</main>



