<?php

use MF\Model\Container;

session_start();
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
        $qtd = $this->view->dados;
    ?>
     <div class="d-flex">
            <div class="content p-1">
                <div class="list-group-item">
                    <div class="d-flex">
                        <div class="mr-auto p-2">
                            <h2 class="display-4 titulo">Listar Mensagens</h2>
                        </div>
                    </div>

                    <?php
                    if (isset($_SESSION['msg'])) {
                        echo $_SESSION['msg'];
                        unset($_SESSION['msg']);
                    }

                    //Receber o número da página
                    $pagina_atual = filter_input(INPUT_GET, 'pagina', FILTER_SANITIZE_NUMBER_INT);
                    $pagina = (!empty($pagina_atual)) ? $pagina_atual : 1;

                    $qnt_result_pg = 10;

                    $inicio = ($qnt_result_pg * $pagina) - $qnt_result_pg;

                    $mensagem = Container::getModel('Contato');

                    $listar_mensagem = $mensagem->listarMensagens($inicio, $qnt_result_pg);
                    
                    if (($listar_mensagem) && (count($listar_mensagem) != 0)) {
                        ?>
                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th>Email</th>
                                        <th>Assunto</th>
                                        <th>Data</th>
                                        <th class="text-center">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                        foreach($listar_mensagem as $mensagem) {
                                        ?>
                                        <tr>
                                            <th><?php echo $mensagem['nome']; ?></th>
                                            <td><?php echo $mensagem['email']; ?></td>
                                            <td><?php echo $mensagem['assunto']; ?></td>
                                            <td><?= date('d/m/Y H:i:s', strtotime( $mensagem['created'])) ?></td>
                                            
                                            <td class="text-center">
                                                <span class="d-none d-md-block">
                                                    <a href="/adm/contato/vis_contato?id=<?=$mensagem['id']?>" class='btn btn-outline-primary btn-sm'>Visualizar</a>
                                                    <a href='/adm/contato/apagar_contato?id=<?=$mensagem['id']?>' class='btn btn-outline-danger btn-sm' data-confirm='Tem certeza de que deseja excluir o item selecionado?'>Apagar</a>
                                                </span>
                                                <div class="dropdown d-block d-md-none">
                                                    <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="acoesListar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        Ações
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="acoesListar">
                                                        <a class='dropdown-item' href='/adm/contato/vis_contato?id=<?=$mensagem['id']?>'>Visualizar</a>
                                                        <a class='dropdown-item' href='/adm/contato/apagar_contato?id=<?=$mensagem['id']?>' data-confirm='Tem certeza de que deseja excluir o item selecionado?'>Apagar</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                    ?>

                                </tbody>
                            </table>
                        <?php
                        $quantidade_pg = ceil( $qtd[0]['qtd'] / $qnt_result_pg);
                        //Limitar os link antes depois
                        $max_links = 2;
                        echo "<nav aria-label='paginacao-blog'>";
                        echo "<ul class='pagination pagination-sm justify-content-center'>";
                        echo "<li class='page-item'>";
                        echo "<a class='page-link' href='/adm/campeonatos?pagina=1' tabindex='-1'>Primeira</a>";
                        echo "</li>";

                        for ($pag_ant = $pagina - $max_links; $pag_ant <= $pagina - 1; $pag_ant++) {
                            if ($pag_ant >= 1) {
                                echo "<li class='page-item'><a class='page-link' href='/adm/campeonatos?pagina=$pag_ant'>$pag_ant</a></li>";
                            }
                        }

                        echo "<li class='page-item active'>";
                        echo "<a class='page-link' href='#'>$pagina</a>";
                        echo "</li>";

                        for ($pag_dep = $pagina + 1; $pag_dep <= $pagina + $max_links; $pag_dep++) {
                            if ($pag_dep <= $quantidade_pg) {
                                echo "<li class='page-item'><a class='page-link' href='/adm/campeonatos?pagina=$pag_dep'>$pag_dep</a></li>";
                            }
                        }

                        echo "<li class='page-item'>";
                        echo "<a class='page-link' href='/adm/campeonatos?pagina=$quantidade_pg'>Última</a>";
                        echo "</li>";
                        echo "</ul>";
                        echo "</nav>";
                        ?>                        
                    </div>
                    <?php
                    } else {
                        ?>
                        <div class="alert alert-danger" role="alert">
                            Nenhum registro encontrado!
                        </div>
                        <?php
                    }

                    ?>
                </div>
            </div>
        </div>

<?php
    } else {
        header('Location: /adm/login');
    }
} else {
    header('Location: /adm/login');
}