<?php 
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
    ?>
    <div class="d-flex">
        <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Cadastrar Campeonato</h2>
                    </div>
                    <div class="p-2">
                        <a class="btn btn-outline-info btn-sm" href="/clarim/adm/campeonatos"> Listar</a>
                    </div>
                </div>
                <hr>
                <?php
                    if(isset($_SESSION['erros'])) {
                        foreach($_SESSION['erros'] as $erro) {
                            echo $erro . "<br>";
                        }
                        unset($_SESSION['erros']);
                    }
                ?>
                <form method="POST" action="/clarim/adm/proc_cad_campeonato">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <span class="text-danger">* </span>
                            <label>
                                Nome:
                            </label>
                            <input name="nome" type="text" class="form-control" 
                            value="<?php if(isset($_SESSION['dados']['nome'])) { echo $_SESSION['dados']['nome']; } ?>"
                            id="nome" placeholder="Nome do usuário" required>
                        </div>
                        <div class="form-group col-md-3">
                            <span class="text-danger">* </span>
                            <label>
                                Estilo:
                            </label>
                            <select class="custom-select" name="estilo" id="estilo">
                                <?php
                                    if(isset($_SESSION['dados']['estilo'])) { $estilo = $_SESSION['dados']['estilo']; } 
                                    if($estilo == 0 ) {
                                        echo "<option>Selecione uma opção</option>";
                                        echo "<option selected value='0'>Pontos Corridos</option>";
                                        echo "<option value='1'>Mata-Mata</option";
                                    } else if ($estilo == 1) {
                                        echo "<option>Selecione uma opção</option>";
                                        echo "<option value='0'>Pontos Corridos</option>";
                                        echo "<option selected value='1'>Mata-Mata</option";
                                    } else {
                                        echo "<option selected>Selecione uma opção</option>";
                                        echo "<option  value='0'>Pontos Corridos</option>";
                                        echo "<option value='1'>Mata-Mata</option";
                                    }
                                ?>
                                
                                >
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <span class="text-danger">* </span>
                            <label>
                                Quantidade de times:
                            </label>
                            <select class="custom-select" name="qtdtimes" id="times" required>
                                <option value='0' selected>Selecione uma opção</option>
                                <option value='32'>32</option>
                                <option value='16'>16</option>
                                <option value='8'>8</option>
                                <option value='4'>4</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label>
                            Regulamento:
                            </label>
                            <textarea name="regulamento" rows="5" class="form-control" id="regulamento"><?php if(isset($_SESSION['dados']['regulamento'])) { echo $_SESSION['dados']['regulamento']; } ?></textarea>
                            
                        </div>
                    </div>
                    <p>
                        <span class="text-danger">* </span>Campo obrigatório
                    </p>
                    <input name="SendCadCamps" id="SendCadCamps"  type="submit" class="btn btn-success" value="Cadastrar"></input>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $("#times").attr('disabled','disabled');
            if ($("#estilo").val() == 0 ) {
                $( "#times" ).prop( "disabled", true );
                $("#times").attr('disabled','disabled');
            } else {
                $("#times").prop( "disabled", false );
            }
            $("#estilo" ).change(function() {
                if ($("#estilo").val() == 0 ){
                    $( "#times" ).prop( "disabled", true );
                    $("#times").attr('disabled','disabled');
                } else {
                    $("#times").prop( "disabled", false );
                }
            });


        });

    </script>


<?php
    unset($_SESSION['dados']);
    } else {
        header('Location: /clarim/adm/login');
    }
} else {
    header('Location: /clarim/adm/login');
}