<?php
    $id = filter_input(INPUT_GET, 'id', FILTER_SANITIZE_NUMBER_INT);
    use MF\Model\Container;
    $camp = Container::getModel('Campeonato');
    $campAtivos = $camp->getCampeonato($id);
?>
<main role="main">
    <?php
        if(count($campAtivos) > 0 ){
    ?>
    <h1><?= $campAtivos[0]['nome'] ?></h1>
    </hr><br>
    <table class="table">
    <thead>
        <tr>
        <th scope="col">Classificação</th>
        <th scope="col">P</th>
        <th scope="col">V</th>
        <th scope="col">D</th>
        <th scope="col">E</th>
        <th scope="col">GP</th>
        <th scope="col">GC</th>
        <th scope="col">SG</th>
        <th scope="col">CV</th>
        <th scope="col">CA</th>
        </tr>
    </thead>
    <tbody>
        <?php
            $classificacao = 1;
            foreach($campAtivos as $time) {
        ?>
        <tr>
            <th scope="row" cols="2">
                <div class="row">
                    <div class="classi"> <?=$classificacao?> </div>
                    <div> <?=$time['time']?> </div>
                </div>
            </th>                    
            <td><?=$time['pontuacao']?></td>
            <td><?=$time['vitorias']?></td>
            <td><?=$time['derrotas']?></td>
            <td><?=$time['empates']?></td>
            <td><?=$time['gol_pro']?></td>
            <td><?=$time['gol_contra']?></td>
            <td><?=$time['saldo_gol']?></td>
            <td><?=$time['cartao_ver']?></td>
            <td><?=$time['cartao_amer']?></td>
        </tr>
        <?php
            $classificacao ++;
            }
        ?>
    </tbody>
    </table>
    <div class="row">
        <p class="lead">
            <a class="btn btn-light btn-lg" href="#" role="button" data-toggle="modal" data-target="#regulamento">Regulamento</a>
        </p>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="regulamento" tabindex="-1" role="dialog" aria-labelledby="regulamentoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="regulamentoLabel">Regulamento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <?= $campAtivos[0]['regulamento'] ?>
            </div>
        </div>
    </div>
    </div>

    <?php
        } else {
            ?>
            <div class="jumbotron">
            <h1 class="display-4">Sentimos muito..</h1>
            <p class="lead">Ainda não temos uma tabela para esse campeonato, fique ligado que em breve vamos disponíbilizar a tabela</p>
            </div>
            <?php
        }
    ?>
</main>