<?php

use MF\Model\Container;

if(isset($_SESSION)) {
    if($_SESSION['logado']) {
        $camp = Container::getModel('Campeonato');
                    $camp->__set('id', $_GET['id']);
                    $jogos = $camp->buscarJogos();
                    if(!$jogos) {
                        $_SESSION['msg'] = "<div class='alert alert-danger'> Defina confrontos os confrontos antes
                        <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
                        <span aria-hidden='true'>&times;</span>
                        </button></div>";
                        echo "<script>location.href='/clarim/adm/campeonatos';</script>";
                        die();                        
                    }
                    
    ?>
    <div class="d-flex">
        <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Novo Jogo</h2>
                    </div>
                    <div class="p-2">
                        <a class="btn btn-outline-info btn-sm" href="/clarim/adm/campeonatos"> Listar</a>
                    </div>
                </div>
                <hr>
                <?php
                if (isset($_SESSION['msg'])) {
                    echo $_SESSION['msg'];
                    unset($_SESSION['msg']);
                }
                    if(isset($_SESSION['erros'])) {
                        foreach($_SESSION['erros'] as $erro) {
                            echo $erro . "<br>";
                        }
                        unset($_SESSION['erros']);
                    }
                ?>
                <div class="container">
                    <div class="row">
                        <div class="form-group">
                            <label>Escolha o jogo</label>
                                <select class="custom-select" name="time1" id="jogo">
                                    <option selected>Selecione o jogo</option>
                                    <?php
                                        foreach ($jogos as $jogo) {
                                            echo "<option value='".$jogo['id']."'>". $jogo['time1']." x ".$jogo['time2']." </option>";
                                        }
                                    ?>
                                </select>
                        </div>
                    </div>
                </div>
                <form method="POST" id="form-jogo">
                    <input type="text" id="id" name="id" value="<?=$_SESSION['dados']['id']?>" hidden>
                    <div class="row">
                        <?php
                            $time = Container::getModel('Time');
                            $times = $time->listarTimesFase($_SESSION['dados']['id']);
                        ?>
                        <div class="container col-md-6">
                            <div class="row">
                                <div class="form-group col-md-8">
                                    <span class="text-danger">* </span>
                                    <label>
                                        Time:
                                    </label>
                                        <select class="custom-select" name="time1" id="time1">
                                            <option selected>Selecione o time</option>
                                            <?php
                                                
                                                foreach($times as $t) {
                                                    echo "<option value='".$t['id']."'>".$t['time']."</option>";
                                                }
                                            ?>
                                        </select>
                                </div>
                                <div class="form-group col-md-4">
                                    <span class="text-danger">* </span>
                                    <label>
                                        Gols:
                                    </label>
                                    <input name="gol1" type="number" min="0" class="form-control" 
                                    value="<?php if(isset($_SESSION['dados']['gol1'])) { echo $_SESSION['dados']['gol1']; } ?>"
                                    id="gol1" placeholder="qtd Gol" requided >
                                </div>
                            </div>
                        </div>
                        <div class="container col-md-6">
                            <div class="row">
                            <div class="form-group col-md-4">
                                    <span class="text-danger">* </span>
                                    <label>
                                        Gols:
                                    </label>
                                    <input name="gol2" type="number" min="0" class="form-control" 
                                    value="<?php if(isset($_SESSION['dados']['gol2'])) { echo $_SESSION['dados']['gol2']; } ?>"
                                    id="gol2" placeholder="qtd Gol" required>
                                </div>
                                <div class="form-group col-md-8">
                                    <span class="text-danger">* </span>
                                    <label>
                                        Time:
                                    </label>
                                    <select class="custom-select" name="time2" id="time2" required>
                                        <option selected>Selecione o time</option>
                                        <?php
                                            
                                            foreach($times as $t) {
                                                echo "<option value='".$t['id']."'>".$t['time']."</option>";
                                            }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            
                        </div>
                    </div>

                    <p>
                        <span class="text-danger">* </span>Campo obrigatório
                    </p>
                    <input name="SendCadJog" id="SendCadJog"  type="button" class="btn btn-success" value="Registrar"></input>
                </form>
            </div>
        </div>
    </div>
    <script  src="../../../public/assets/js/jogo_mata_fase.js" ></script>
    <?php
    } else {
        header('Location: /clarim/adm/login');
    }
} else {
    header('Location: /clarim/adm/login');
}