<?php

use MF\Model\Container;

session_start();
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
        $campeonato = $this->view->dados;
        $camp = Container::getModel('Campeonato');
        $fase = $camp->getFase($campeonato->__get('id'));
    ?>
<div class="d-flex">
        <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Detalhes do Campeonato</h2>
                    </div>
                   
                    <div class="p-2">
                        <span class="d-none d-md-block">
                            <a class='btn btn-outline-success btn-sm' role="button" data-toggle="modal" data-target="#cadTime">Novo Time</a>
                            <a class="btn btn-outline-info btn-sm" href="/clarim/adm/campeonatos"> Listar</a>
                            <a class="btn btn-outline-warning btn-sm" href="/clarim/adm/campeonatos/edit_campeonato?id=<?=$campeonato->__get('id')?>"> Editar</a>
                            <a class="btn btn-outline-danger btn-sm disabled" href="/clarim/adm/campeonato/apagar_campeonato?id=<?=$campeonato->__get('id')?>" data-confirm="Tem certeza que deseja excluir o item seleconado?" >Apagar</a>
                        </span>
                        <div class="dropdown d-block d-md-none">
                            <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="acoesListar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ações
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="acoesListar">
                                <a class="dropdown-item" role="button" data-toggle="modal" data-target="#cadTime">Novo Time</a>
                                <a class="dropdown-item" href="/clarim/adm/campeonatos">Listar</a>
                                <a class="dropdown-item" href="/clarim/adm/campeonatos/edit_campeonato?id=<?=$campeonato->__get('id')?>">Editar</a>
                                <a class="dropdown-item disabled" href="/clarim/adm/campeonato/apagar_campeonato?id=<?=$campeonato->__get('id')?>"  data-confirm="Tem certeza que deseja excluir o item seleconado?" disabled >Apagar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <?php
                        if (isset($_SESSION['msg'])) {
                            echo $_SESSION['msg'];
                            unset($_SESSION['msg']);
                        }
                    ?>
                <hr>
                <dl class="row">
                    <dt class="col-sm-3">ID</dt>
                    <dd class="col-sm-9"><?= $campeonato->__get('id') ?></dd>

                    <dt class="col-sm-3">Nome</dt>
                    <dd class="col-sm-9">
                        <?php                         
                            echo $campeonato->__get('nome');
                        ?></dd>

                    <dt class="col-sm-3">Tipo</dt>
                <dd class="col-sm-9">
                    <?php
                    if($campeonato->__get('estilo') == 0 ) {
                        echo 'Pontos Corridos'; 
                    } else {
                        echo  'Mata-Mata';
                        echo '</dd>';
                        ?>
                        <dt class="col-sm-3">Fase</dt>
                        <dd class="col-sm-9">
                        <?php
                        
                            echo $fase[0]['nome'] . " - ";
                            
                            
                        echo "<a href='/clarim/adm/confrontos?id=".$campeonato->__get('id')."' class='badge badge-pill badge-success'> Definir Confrontos</a>"; 
                        echo '</dd>';
                    }
                    ?>
                
            

                    <dt class="col-sm-3">Regulamento</dt>
                    <dd class="col-sm-9"><?= $campeonato->__get('regulamento') ?></dd>

                    <dt class="col-sm-3">Ativo</dt>
                    <dd class="col-sm-9"> 
                    <?php 
                        if ($campeonato->__get('finalizado') != 0 ) {
                            echo "<span class='badge badge-pill badge-danger'> Inativo </span>"; 

                        } else {
                            echo "<span class='badge badge-pill badge-success'> Ativo</span>"; 
                        }
                    ?>
                    </dd>
                </dl> 
            </div>
        </div>
    </div>
    <?php 
        $time = Container::getModel('Time');
        $times = $time->listarTimesSemFiltro();
    ?>
    
    <!-- Modal -->
    <div class="modal fade" id="cadTime" tabindex="-1" role="dialog" aria-labelledby="regulamentoLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="regulamentoLabel">Cadastrar Novo Time</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                <form method="POST" action="/clarim/adm/campaonato/time">
                    <input type="text" id="idc" name="idc" value="<?=$campeonato->__get('id')?>" hidden>
                        <div class="row">
                            <div class="form-group col-md-12">
                                    <label>
                                        Time:
                                    </label>
                                    
                                    <select class="custom-select" name="idt" id="inputGroupSelect01">
                                        <option selected>Selecione o time</option>
                                        <?php
                                            
                                            foreach($times as $t) {
                                              echo "<option value='".$t['id']."'>".$t['time']."</option>";
                                            }
                                        ?>
                                </select>
                            </div>
                        </div>
                        <input name="SendCadTime" id="SendCadTime"  type="submit" class="btn btn-success" value="Registrar"></input>
                    </form>
                </div>
            </div>
        </div>
    </div>
            

<?php
    } else {
        header('Location: /clarim/adm/login');
    }
} else {
    header('Location: /clarim/adm/login');
}