<?php
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
        $video = $this->view->dados;
    ?>
<div class="d-flex">
        <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Detalhes do Vídeo</h2>
                    </div>
                    <div class="p-2">
                        <span class="d-none d-md-block">
                            <a class="btn btn-outline-info btn-sm" href="/clarim/adm/videos"> Listar</a>
                            <a class="btn btn-outline-warning btn-sm" href="/clarim/adm/video/edit_video?id=<?=$video->__get('id')?>"> Editar</a>
                            <a class="btn btn-outline-danger btn-sm" href="/clarim/adm/video/apagar_video?id=<?=$video->__get('id')?>" data-confirm="Tem certeza que deseja excluir o item seleconado?">Apagar</a>
                        </span>
                        <div class="dropdown d-block d-md-none">
                            <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="acoesListar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ações
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="acoesListar">
                                <a class="dropdown-item" href="/clarim/adm/videos">Listar</a>
                                <a class="dropdown-item" href="/clarim/adm/video/edit_video?id=<?=$video->__get('id')?>">Editar</a>
                                <a class="dropdown-item" href="/clarim/adm/video/apagar_video?id=<?=$video->__get('id')?>"  data-confirm="Tem certeza que deseja excluir o item seleconado?">Apagar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <dl class="row">
                    <dt class="col-sm-3">ID</dt>
                    <dd class="col-sm-9"><?= $video->__get('id') ?></dd>

                    <dt class="col-sm-3">Nome</dt>
                    <dd class="col-sm-9">
                        <?php                         
                            echo $video->__get('nome');
                        ?>
                    </dd>

                    <dt class="col-sm-3">Vídeo</dt>
                    <dd class="col-sm-9">
                        <?php                         
                            echo $video->__get('link');
                        ?>
                    </dd>
                </dl> 
            </div>
        </div>
    </div>

<?php
    } else {
        header('Location: /clarim/adm/login');
    }
} else {
    header('Location: /clarim/adm/login');
}