   <main role="main">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target='#myCarousel' data-slide-to='$cont_marc'></li>                 
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="featurette-image img-fluid mx-auto" src="public/assets/imagens/index/fundo.jpg">
                </div>
            </div>
        </div>
        <div class="jumbotron sobre-empresa">
            <div class="container">
                <div class="row featurette">
                    <div class="col-md-7 order-md-2 emp-text-mod-um">
                        <h2 class="featurette-heading">CLARIM E-SPORTS</h2>
                        <p class="lead">Aqui vai toda a apresentação da empresa pode escrever o texto </p>
                    </div>
                    <div class="col-md-5 order-md-1 emp-img-mod-um">
                    <img class="featurette-image img-fluid mx-auto" src="public/assets/imagens/index/logoClarim.jpg">
                    </div>
                </div>
            </div>
        </div>
        <div class="jumbotron depoimento">
            <div class="container">
                <h2 class="display-4 text-center" style="margin-bottom: 40px; color: #FFF;">Conheça nosso trabalho</h2>
                <p class="lead text-center" style="margin-bottom: 40px; color: #FFF;">Últimos conteúdos adicionados</p>
                <div class="card-deck">
                    <?php

                        use MF\Model\Container;

                        $contador = 1;
                        $videos = Container::getModel('Video');
                        $videos = $videos->listarUltimos();

                        foreach ($videos as $v) {
                            $aling ;
                            if ($contador == 1 ){
                                $aling = "left";
                            } else if ($contador == 2) {
                                $aling = "center";
                            } else if ($contador == 3) {
                                $aling = "right";
                            }
                            ?>
                            <div class="card text-center dep-<?=$aling?>">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <?=$v['link'] ?>
                                </div>
                            </div>
                        <?php
                        $contador ++;
                        }
                        ?>						
                    </div>
                </div>
            </div>
        </div>
        
    </main>