<main role="main">
    <div class="jumbotron sobre-empresa" style="padding-bottom: 1rem; margin-bottom: 0px;">
        <div class="container">
            <h2 class="display-4 text-center">Sobre Nós</h2>
        </div>
    </div>
    <div class="jumbotron sobre-empresa">
        <div class="container">
            <div class="row featurette">
                <div class="col-md-7 order-md-2 emp-text-mod-um">
                    <h2 class="featurette-heading">Daniel Nicastro</h2>
                    <p class="lead">Description Here</p>
                </div>
                <div class="col-md-5 order-md-1 emp-img-mod-um">
                <img class="featurette-image img-fluid mx-auto" src="../../../public/assets/imagens/index/dani.jpg">
                </div>
            </div>
        </div>
    </div>
    <div class="jumbotron sobre-empresa">
        <div class="container">
            <div class="row featurette">
                <div class="col-md-7 emp-text-mod-dois">
                    <h2 class="featurette-heading">Alberto Rosa</h2>
                    <p class="lead">Description Here</p>
                </div>
                <div class="col-md-5 emp-img-mod-dois">
                <img class="featurette-image img-fluid mx-auto" src="../../../public/assets/imagens/index/beto.jpg">
                </div>
            </div>
        </div>
    </div>
</main>