<?php 
session_start();
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
        $time = $this->view->dados;
    ?>
    <div class="d-flex">
        <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Editar Time</h2>
                    </div>
                    <div class="p-2">
                        <a class="btn btn-outline-info btn-sm" href="/adm/times"> Listar</a>
                    </div>
                </div>
                <hr>
                <?php
                    if(isset($_SESSION['erros'])) {
                        foreach($_SESSION['erros'] as $erro) {
                            echo $erro . "<br>";
                        }
                        unset($_SESSION['erros']);
                    }
                ?>
                <form method="POST" action="/adm/proc_edit_time">
                    <input id="id" name="id" type="text" value="<?php
                        if(isset($_SESSION['dados']['id'])) {
                            echo $_SESSION['dados']['id'];
                        } else {
                            echo  $time->__get('id');
                        }?>                            
                        " hidden>

                    <div class="form-group col-md-12">
                        <span class="text-danger">* </span>
                        <label>
                            Nome:
                        </label>
                        <input name="time" type="text" class="form-control" 
                        value="<?php if(isset($_SESSION['dados']['time'])) { echo $_SESSION['dados']['time']; } else {
                            echo  $time->__get("time");
                        } ?>"
                        id="time" placeholder="Nome do time" required>
                    </div>
                    <p>
                        <span class="text-danger">* </span>Campo obrigatório
                    </p>
                    <input name="SendCadTime" id="SendCadTime"  type="submit" class="btn btn-warning" value="Salvar"></input>
                </form>
            </div>
        </div>
    </div>
    
<?php
    unset($_SESSION['dados']);
    } else {
        header('Location: /adm/login');
    }
} else {
    header('Location: /adm/login');
}