<?php
use MF\Model\Container;
?>
<link href='/clarim/public/assets/css/agenda/agenda.css' rel='stylesheet' />

  <div id='loading'>loading...</div>

  <div id='calendar'></div>
  <div id="teste" hidden>Teste</div>

  <!-- Modal -->
  <div class="modal fade" id="visualizar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Detalhes do evento</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <dl class="row">
            <dt class="col-sm-3">ID do evento</dt>
            <dd class="col-sm-9" id="id"></dd>
            <dt class="col-sm-3">Título</dt>
            <dd class="col-sm-9" id="title"></dd>
            <dt class="col-sm-3">Ínicio</dt>
            <dd class="col-sm-9" id="start"></dd>
            <dt class="col-sm-3">Fim</dt>
            <dd class="col-sm-9" id="end"></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="cadastrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cadastrar evento</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <span id="msg-cad"></span>
          <form id="addEvent" method="POST" enctype="multipart/form-data">
            <input type="hidden" value="" id="dataEvent" name="dataEvent">
            <div class="form-group row">
              <div class="col">
                <label >Título do evento</label>
                <input type="text" class="form-control" id="titulo" name ='titulo' placeholder="titulo do evento">
              </div>
              <div class="col">
                <label for="horario">Horários disponíveis</label>
                <select  class="custom-select" id="horario" name="horario">
                <option value='0'> Selecione um horário disponível</option>
                <?php
                /*
                  $horario = Container::getModel('Time');
                  $horarios = $horario->getHorariosDisp();
                  foreach($horarios as $h) {
                    echo "<option value='{$h['id']}'> {$h['horario']}</option> ";
                    ?>
                    <?php
                  }
                  */
                ?>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <div class="col">
                <label >Time 1</label>
                <?php
                  $user = Container::getModel('Usuario');
                  $user->__set('id', $_SESSION['id']);
                  $time = $user->getTime();
                  
                  if (count($time) > 0) {
                    ?>
                      <input type="text" value='<?=$time[0]['time']?>' class="form-control" id="time1" name="time1" readonly>
                    <?php
                  }else {
                ?>
                    <input type="text" class="form-control" id="time1" name ='time1' placeholder="Time 1">
                <?php
                  }
                ?>
              </div>
              <div class="col">
                <label >Time 2</label>
                
                <input type="text" class="form-control" id="time2" name="time2" placeholder="Time 2">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" id="cadEvent" value="cadEvent" class="btn btn-success">Agendar</button>
            </div> 
          </form>
        </div>
      </div>
    </div>
  </div>
<script  src="/clarim/public/assets/js/agenda/agenda.js" ></script>

