<link href='/clarim/public/assets/css/agenda/agenda.css' rel='stylesheet' />

  <div id='loading'>loading...</div>

  <div id='calendar'></div>
  <div id="teste" hidden>Teste</div>

  <!-- Modal -->
  <div class="modal fade" id="visualizar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Detalhes do evento</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <dl class="row">
            <dt class="col-sm-3">ID do evento</dt>
            <dd class="col-sm-9" id="id"></dd>
            <dt class="col-sm-3">Título</dt>
            <dd class="col-sm-9" id="title"></dd>
            <dt class="col-sm-3">Ínicio</dt>
            <dd class="col-sm-9" id="start"></dd>
            <dt class="col-sm-3">Fim</dt>
            <dd class="col-sm-9" id="end"></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="cadastrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cadastrar evento</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group row">
              <div class="col">
                <label for="title">Título do evento</label>
                <input type="text" class="form-control" id="title" placeholder="Título do evento">
              </div>
              <div class="col">
                <label for="title">Horários disponíveis</label>
                <input type="text" class="form-control" id="title" placeholder="Título do evento">
              </div>
            </div>
            <div class="form-group row">
              <div class="col">
                <label for="title">Start</label>
                <input type="text" class="form-control" id="title" placeholder="Título do evento">
              </div>
              <div class="col">
                <label for="title">End</label>
                <input type="text" class="form-control" id="title" placeholder="Título do evento">
              </div>
            </div>
            
          </form>
        </div>
      </div>
    </div>
  </div>
<script  src="/clarim/public/assets/js/agenda/agenda.js" ></script>

