<?php

use MF\Model\Container;

session_start();
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
    ?>
    <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Dashboard</h2>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-success text-white">
                            <div class="card-body">
                                <i class="fas fa-users fa-3x"></i>
                                <h6 class="card-title">Usuários</h6>
                                <h2 class="lead">
                                <?php
                                    $camp = Container::getModel('Usuario');
                                    $qtd = $camp->getTotalRegistros();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-danger text-white">
                            <div class="card-body">
                                <i class="fas fa-file fa-3x"></i>
                                <h6 class="card-title">Campeonatos ativos</h6>
                                <h2 class="lead">
                                <?php
                                    $camp = Container::getModel('Campeonato');
                                    $qtd = $camp->getTotalCamp();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-warning text-white">
                            <div class="card-body">
                                <i class="fas fa-eye fa-3x"></i>
                                <h6 class="card-title">Times cadastrados</h6>
                                <h2 class="lead">
                                <?php
                                    
                                    $time = Container::getModel('Time');
                                    $qtd = $time->getTotalTime();
                                    echo $t;
                                    
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-info text-white">
                            <div class="card-body">
                                <i class="fas fa-comments fa-3x"></i>
                                <h6 class="card-title">Campeonatos finalizados</h6>
                                <h2 class="lead">
                                <?php
                                    $camp = Container::getModel('Campeonato');
                                    $qtd = $camp->getTotalCampFinalizado();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>
    <?php
    } else {
        header('Location: /adm/login');
    }
} else {
    header('Location: /adm/login');
}