<?php

use MF\Model\Container;

session_start();
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
    ?>
    <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Dashboard</h2>
                    </div>
                </div>
                <p>Usuários</p>
                <div class="row mb-3">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-success text-white">
                            <div class="card-body">
                                <i class="fas fa-users fa-3x"></i>
                                <h6 class="card-title">Usuários</h6>
                                <h2 class="lead">
                                <?php
                                    $camp = Container::getModel('Usuario');
                                    $qtd = $camp->getTotalRegistros();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-danger text-white">
                            <div class="card-body" id="link-senha">
                                <i class="fas fa-file fa-3x"></i>
                                <h6 class="card-title">Solicitação de senha</h6>
                                <h2 class="lead">
                                <?php
                                    $tot = Container::getModel('Usuario');
                                    $qtd = $tot->solicitacaoReset();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    
                    
                </div>
                <p>Campeonatos</p>
                <div class="row mb-3">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-success text-white">
                            <div class="card-body">
                                <i class="fas fa-file fa-3x"></i>
                                <h6 class="card-title">Campeonatos ativos</h6>
                                <h2 class="lead">
                                <?php
                                    $camp = Container::getModel('Campeonato');
                                    $qtd = $camp->getTotalCamp();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-warning text-white">
                            <div class="card-body">
                                <i class="fas fa-eye fa-3x"></i>
                                <h6 class="card-title">Times cadastrados</h6>
                                <h2 class="lead">
                                <?php
                                    $time = Container::getModel('Time');
                                    $t = $time->getTotal();
                                    echo $t[0]['qtd'];
                                    
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-info text-white">
                            <div class="card-body">
                                <i class="fas fa-comments fa-3x"></i>
                                <h6 class="card-title">Campeonatos finalizados</h6>
                                <h2 class="lead">
                                <?php
                                    $camp = Container::getModel('Campeonato');
                                    $qtd = $camp->getTotalCampFinalizado();
                                    echo $qtd[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <p>Mensagens    </p>
                <?php
                    $mensagens = Container::getModel('Contato');
                    $naoLidas = $mensagens->getNaoLidas();
                    $naoResp = $mensagens->getNaoResp();
                    $msgTotal = $mensagens->getTotal();
                    $lidaResp = $mensagens->getLidasResp();
                ?>
                <div class="row mb-3">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-success text-white">
                            <div class="card-body" id="link-mensagens">
                                <i class="fas fa-users fa-3x"></i>
                                <h6 class="card-title">Não lidas</h6>
                                <h2 class="lead">
                                <?php
                                    echo $naoLidas[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-danger text-white">
                            <div class="card-body">
                                <i class="fas fa-file fa-3x"></i>
                                <h6 class="card-title">Não respondidas</h6>
                                <h2 class="lead">
                                <?php
                                    echo $naoResp[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-warning text-white">
                            <div class="card-body">
                                <i class="fas fa-eye fa-3x"></i>
                                <h6 class="card-title">Total</h6>
                                <h2 class="lead">
                                <?php
                                    echo $msgTotal[0]['qtd'];
                                    
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card bg-info text-white">
                            <div class="card-body">
                                <i class="fas fa-comments fa-3x"></i>
                                <h6 class="card-title">lidas e respondidas</h6>
                                <h2 class="lead">
                                <?php
                                    echo $lidaResp[0]['qtd'];
                                ?>
                                </h2>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>  
    </div>
    <script>
        $("#link-mensagens").on('click', function () {
            window.location.href = "/clarim/adm/contato";
        });

        $("#link-senha").on('click', function () {
            window.location.href = "/clarim/adm/listarSolicitacaoSenha";
        });
    </script>
    <?php
    } else {
        header('Location: /clarim/adm/login');
    }
} else {
    header('Location: /clarim/adm/login');
}