<?php 
    session_start();
?>
<body class="text-center corpoLogin">
    <form class="form-signin" method="POST" action="/adm/valida">
        <img class="mb-4" src="/assets/imagens/index/logoClarim.jpg" alt="Clarim" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Área Restrita</h1>
        <?php
            if (isset($_SESSION['msg'])) {
                echo $_SESSION['msg'];
                unset($_SESSION['msg']);
            }
            if ($this->view->login == 'erro') {
        ?>
            <span class="text text-danger">*E-mail ou senha inválidos</span>    
        <?php
            }
        ?>
        
        <div class="form-group">
            <label>Usuário</label>
            <input name="usuario" type="text" class="form-control" placeholder="Digite o usuário" required>               
        </div>
        <div class="form-group">
            <label>Senha</label>
            <input name="senha" type="password" class="form-control" placeholder="Digite a senha" required>
            <small>*senha padrão = 12345678</small>
        </div>
        <input type="submit" class="btn btn-lg btn-primary btn-block" value="Acessar" name="SendLogin">
    </form>
</body>