<?php 
if(isset($_SESSION)) {
    if($_SESSION['logado']) {
        $user = $this->view->dados;
    ?>
    <div class="d-flex">
        <div class="content p-1">
            <div class="list-group-item">
                <div class="d-flex">
                    <div class="mr-auto p-2">
                        <h2 class="display-4 titulo">Detalhes do Usuário</h2>
                    </div>
                    <div class="p-2">
                        <span class="d-none d-md-block">
                            <a class="btn btn-outline-info btn-sm" href="/clarim/adm/usuarios"> Listar</a>
                            <a class="btn btn-outline-warning btn-sm" href="/clarim/adm/usuarios/edit_user?id=<?=$user->__get('id')?>"> Editar</a>
                            <a href="/clarim/adm/usuarios/resetar?id=<?=$user->__get('id')?>" class='btn btn-outline-secondary btn-sm'>Resetar</a>
                            <a class="btn btn-outline-danger btn-sm disabled" href="/clarim/adm/apagar_user?id=<?=$user->__get('id')?>" data-confirm="Tem certeza que deseja excluir o item seleconado?">Apagar</a>
                        </span>
                        <div class="dropdown d-block d-md-none">
                            <button class="btn btn-primary dropdown-toggle btn-sm" type="button" id="acoesListar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Ações
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="acoesListar">
                                <a class="dropdown-item" href="/clarim/adm/usuarios">Listar</a>
                                <a class="dropdown-item" href="/clarim/adm/usuarios/edit_user?id=<?=$user->__get('id')?>">Editar</a>
                                <a class='dropdown-item' href='/clarim/adm/usuarios/resertar?id=<?=$user->__get('id')?>'>Resetar</a>
                                <a class="dropdown-item disabled" href="/clarim/adm/apagar_user?id=<?=$user->__get('id')?>"  data-confirm="Tem certeza que deseja excluir o item seleconado?">Apagar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <dl class="row">
                    <dt class="col-sm-3">ID</dt>
                    <dd class="col-sm-9"><?= $user->__get('id') ?></dd>

                    <dt class="col-sm-3">Nome</dt>
                    <dd class="col-sm-9">
                        <?php                         
                            echo $user->__get('nome');
                        ?></dd>
                    <dt class="col-sm-3">Email</dt>
                    <dd class="col-sm-9"><?= $user->__get('email') ?></dd>

                    <dt class="col-sm-3">Primeiro Acesso</dt>
                    <dd class="col-sm-9"> 
                    <?php 
                        if ($user->__get('primeiro_acesso') == 0 ) {
                            echo "<span class='badge badge-pill badge-danger'> Necessita trocar a senha </span>"; 

                        } else {
                            echo "<span class='badge badge-pill badge-success'> Usuário Ativo</span>"; 
                        }
                    ?>
                    </dd>
                    <dt class="col-sm-3">Perfil</dt>
                    <dd class="col-sm-9"><?= $user->__get('perfil') ?></dd>

                    <?php if ($user->__get('time') != ''){ ?>
                        <dt class="col-sm-3">Meu Time</dt>
                        <dd class="col-sm-9"><?= $user->__get('time') ?></dd>
                    <?php } ?>
                </dl> 
            </div>
        </div>
    </div>

<?php
    } else {
        header('Location: /clarim/adm/login');
    }
} else {
    header('Location: /clarim/adm/login');
}