    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="/clarim/public/assets/js/scrollreveal.min.js"></script>
    <script  src="/clarim/public/assets/js/dashboard.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
    
    
    <footer class="footer bg-primary fixed-bottom">
        <div class="container text-center">
            Clarim | 3S Tecnology
        </div>
    </footer>
</html>