<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Clarim</title>
        <link rel="canonical" href="#"/>
        <meta name="robots" content="clarim" />
        <meta name="keywords" content="clarim">
        <meta name="description" content="clarim">
        <meta name="author" content="sanDev">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        
        <link rel="stylesheet" href="/clarim//public/assets/css/ionicons.min.css">
        <link rel="stylesheet" href="/clarim//public/assets/css/personalizado.css">
        <link rel="icon" href="/clarim//public/assets/imagens/icone/favicon.ico">
        <link rel="stylesheet" href="/clarim//public/assets/css/signin.css">
        <link rel="stylesheet" href="/clarim/public/assets/css/dashboard.css">

        <link href='/clarim/public/assets/css/lib/main.css' rel='stylesheet' />
        <script src='/clarim/public/assets/css/lib/main.js'></script>
        <script src='/clarim/public/assets/css/lib/locales/pt-br.js'></script>
        <script src='/clarim/public/assets/css/lib/locales-all.min.js'></script>
        <script src='/clarim/public/assets/css/lib/locales-all.js'></script>
    </head>
