<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Clarim</title>
        <link rel="canonical" href="#"/>
        <meta name="robots" content="clarin" />
        <meta name="keywords" content="clarim">
        <meta name="description" content="clarim">
        <meta name="author" content="sanDev">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script  src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="http://code.jquery.com/jquery-1.11.1.js"></script>
        <link rel="stylesheet" href="/clarim//public/assets/css/ionicons.min.css">
        <link rel="stylesheet" href="/clarim//public/assets/css/personalizado.css">
        <link rel="icon" href="/clarim//public/assets/imagens/icone/favicon.ico">
        <link rel="stylesheet" href="/clarim//public/assets/css/signin.css">
        <link rel="stylesheet" href="/clarim/public/assets/css/dashboard.css">
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

        <link href='/clarim/public/assets/css/lib/main.css' rel='stylesheet' />
        <script src='/clarim/public/assets/css/lib/main.js'></script>
        <script src='/clarim/public/assets/css/lib/locales/pt-br.js'></script>
        <script src='/clarim/public/assets/css/lib/locales-all.min.js'></script>
        <script src='/clarim/public/assets/css/lib/locales-all.js'></script>
    </head>
