<header>
<nav class="navbar navbar-expand-lg navbar-dark navbar-primary fixed-top bg-primary">
  <a class="navbar-brand" href="/clarim/">Clarim</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/clarim/">Home </a>
      </li>
      <?php
        use MF\Model\Container;
        $camp = Container::getModel('Campeonato');
        $campAtivos = $camp->getCampeonatos();
      ?>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CAMPEONATOS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <?php
            foreach($campAtivos as $cam) {
              echo '<a class="dropdown-item" href="/clarim/campeonato?id='.$cam['id'].'">'.$cam['nome'].'</a>';
            }
          ?>
          <a class="dropdown-item" href="/clarim/campeonato/listarUltimas">Últimas Edições</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/clarim/sobreNos">SOBRE NÓS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/clarim/contato">CONTATO</a>
      </li>
    </ul>
      <div class="my-2 my-lg-0">
        <a class="nav-link text-light" href="/clarim/adm/login">LOGIN</a>
      </div>
  </div>
  
</nav>
</header>