<nav class="navbar navbar-expand navbar-dark bg-primary">
    <a class="sidebar-toggle text-light mr-3">
        <span class="navbar-toggler-icon"></span>
    </a>
    <a class="navbar-brand" href="/adm/home">Clarim</a>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle menu-header" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                    <img class='rounded-circle' src='/assets/imagens/icone_usuario.png' width='20' height='20'>
                     &nbsp;<span class="d-none d-sm-inline">teste</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href='/visualizar/vis_perfil'><i class="fas fa-user"></i> Perfil</a>
                    <a class="dropdown-item" href="/adm/sair"><i class="fas fa-sign-out-alt"></i> Sair</a>
                </div>
            </li>
        </ul>                
    </div>
</nav>  
<div class="d-flex">
    <nav class="sidebar">
        <ul class="list-unstyled">
            <li><a href="/adm/home"> Dashboard</a></li>
            <li><a href="/adm/campeonatos"> Campeonatos</a></li>
            <li><a href="/adm/times"> Times</a></li>
            <li><a href="/adm/usuarios"> Usuários</a></li>
            <li><a href="/adm/sair"> sair</a></li>
        </ul>
    </nav>