<?php
    if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
?>
<nav class="navbar navbar-expand navbar-dark bg-primary">
    <a class="sidebar-toggle text-light mr-3">
        <span class="navbar-toggler-icon"></span>
    </a>
    <a class="navbar-brand" href="/clarim/adm/home">Clarim</a>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle menu-header" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">
                    <img class='rounded-circle' src='/clarim/public/assets/imagens/icone_usuario.png' width='20' height='20'>
                     &nbsp;<span class="d-none d-sm-inline"><?=$_SESSION['nome'] ?></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href='/clarim/perfil?id=<?=$_SESSION['id'] ?>'><i class="fas fa-user"></i> Perfil</a>
                    <a class="dropdown-item" href="/clarim/adm/sair"><i class="fas fa-sign-out-alt"></i> Sair</a>
                </div>
            </li>
        </ul>                
    </div>
</nav>  
<div class="d-flex">
    <nav class="sidebar">
        <ul class="list-unstyled">
            <?php
                
                if(isset($_SESSION['logado'])) { 
                    if (in_array("dashboard", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/home"> Dashboard</a></li>
                        <?php 
                    } 
                    if (in_array("agenda", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/agenda"> Agenda</a></li>
                        <?php 
                    } 
                    if (in_array("list_campeonato", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/campeonatos"> Campeonatos</a></li>
                        <?php 
                    } 
                    if (in_array("list_camp_finalizado", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/campeonatos_fin"> Campeonatos Finalizados</a></li>
                        <?php 
                    } 
                    if (in_array("listar_jogos", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/jogos"> Jogos</a></li>
                        <?php 
                    } 
                    if (in_array("list_mensagens", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/contato"> Mensagens</a></li>
                        <?php 
                    } 
                    if (in_array("list_times", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/times"> Times</a></li>
                        <?php 
                    } 
                    if (in_array("list_usuario", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/usuarios"> Usuários</a></li>
                        <?php 
                    } 
                    if (in_array("list_video", $_SESSION['permissoes']['permissao'])) { 
                        ?>
                        <li><a href="/clarim/adm/videos"> Vídeos</a></li>
                        <?php 
                    } 
                    } else {
                        header('Location: /clarim/adm/login');
                    }
                ?>
            <li><a href="/clarim/adm/sair"> Sair</a></li>
        </ul>
    </nav>