<header>
<nav class="navbar navbar-expand-lg navbar-dark navbar-primary fixed-top bg-primary">
  <a class="navbar-brand" href="#">Clarim</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/campeonato"> CAMPEONATOS </a>
      </li>     
      <li class="nav-item">
        <a class="nav-link" href="/sobreNos">SOBRE NÓS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contato">CONTATO</a>
      </li>
    </ul>
  </div>
</nav>
</header>